// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VShop.ProductApi.Context;

#nullable disable

namespace VShop.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240327010002_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VShop.ProductApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Smartphones"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Notebook"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Clothes"
                        });
                });

            modelBuilder.Entity("VShop.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long>("Stock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple iPhone 13 (128 GB) - Luz das estrelas",
                            ImageUrl = "https://m.media-amazon.com/images/I/41Zbbl4P+LL._AC_SX342_SY445_.jpg",
                            Name = "Iphone 13",
                            Price = 3699.99m,
                            Stock = 10L
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Celular Samsung Galaxy S23 5G, 512GB, 8GB RAM, Câmera Tripla 50MP+12+10, Tela Infinita de 6.1 Preto",
                            ImageUrl = "https://samsungbrshop.vtexassets.com/arquivos/ids/223871-800-auto?v=638334152107230000&width=800&height=auto&aspect=true",
                            Name = "Samsung Galaxy S23",
                            Price = 5999.89m,
                            Stock = 20L
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Smartphone Xiaomi Redmi 12 4G 256GB - 8GB Ram (Versao Global) (Midnight Black)",
                            ImageUrl = "https://m.media-amazon.com/images/I/61t99wqLeaL.__AC_SX300_SY300_QL70_ML2_.jpg",
                            Name = "Xiaomi Redmi 12",
                            Price = 19.99m,
                            Stock = 100L
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Apple notebook MacBook Air (de 13 polegadas, Processador M1 da Apple com CPU 8‑core e GPU 7‑core, 8 GB RAM, 256 GB) - Prateado",
                            ImageUrl = "https://m.media-amazon.com/images/I/41-RhQeujUL.__AC_SY445_SX342_QL70_ML2_.jpg",
                            Name = "Macbook Air - 13",
                            Price = 6649.05m,
                            Stock = 5L
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Camisa Camiseta Masculina Slim Voker Premium 100% Algodão.",
                            ImageUrl = "https://m.media-amazon.com/images/I/415M8ksnThL._AC_SX385_.jpg",
                            Name = "Camisa Masculina Slim Voker",
                            Price = 60.00m,
                            Stock = 15L
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Camisa Camiseta Masculina Slim Voker Premium 100% Algodão.",
                            ImageUrl = "https://m.media-amazon.com/images/I/41vSsY5uVDL._AC_SX385_.jpg",
                            Name = "Camisa branca",
                            Price = 60.00m,
                            Stock = 25L
                        });
                });

            modelBuilder.Entity("VShop.ProductApi.Models.Product", b =>
                {
                    b.HasOne("VShop.ProductApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VShop.ProductApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
